import type { LucideIcon } from "lucide-react";
import {
  BookOpen,
  Building2,
  CalendarCheck,
  CreditCard,
  FileBarChart,
  GraduationCap,
  LayoutDashboard,
  MessageSquareWarning,
  Megaphone,
  Receipt,
  Settings,
  Users,
} from "lucide-react";

export type NavItem = {
  label: string;
  href: string;
  icon: LucideIcon;
  group?: string;
  children?: NavItem[];
  isSubmenu?: boolean;
};

export const navByRole: Record<string, NavItem[]> = {
  SUPER_ADMIN: [
    { label: "Dashboard", href: "/super-admin/dashboard", icon: LayoutDashboard },
  ],
  SCHOOL_ADMIN: [
    { label: "Dashboard", href: "/admin/dashboard", icon: LayoutDashboard, group: "1. Admin" },
    { label: "Reception", href: "/admin/reception", icon: Users, group: "1. Admin" },
    {
      label: "Students",
      href: "/admin/students",
      icon: Users,
      group: "1. Admin",
      children: [
        { label: "All Students", href: "/admin/students", icon: Users, isSubmenu: true },
        { label: "Admissions", href: "/admin/students/admissions", icon: GraduationCap, isSubmenu: true },
        { label: "Transfers", href: "/admin/students/transfers", icon: GraduationCap, isSubmenu: true },
        { label: "Student Settings", href: "/admin/settings/students", icon: Settings, isSubmenu: true },
      ],
    },
    { label: "Parents", href: "/admin/parents", icon: Users, group: "1. Admin" },
    { label: "Teachers", href: "/admin/teachers", icon: GraduationCap, group: "1. Admin" },
    { label: "Driver & Transport", href: "/admin/transport", icon: Building2, group: "1. Admin" },
    { label: "Finance", href: "/admin/finance", icon: CreditCard, group: "2. Finance" },
    { label: "Fee Group & Structure", href: "/admin/fees", icon: CreditCard, group: "2. Finance" },
    { label: "Bills", href: "/admin/invoices", icon: Receipt, group: "2. Finance" },
    { label: "Payments", href: "/admin/payments", icon: CreditCard, group: "2. Finance" },
    { label: "Academics", href: "/admin/academics", icon: BookOpen, group: "3. Academics" },
    { label: "Classes & Arms", href: "/admin/classes", icon: Building2, group: "3. Academics" },
    { label: "Subjects", href: "/admin/subjects", icon: BookOpen, group: "3. Academics" },
    { label: "Attendance", href: "/admin/attendance", icon: CalendarCheck, group: "3. Academics" },
    { label: "Results", href: "/admin/results", icon: FileBarChart, group: "3. Academics" },
    { label: "LMS", href: "/admin/lms", icon: BookOpen, group: "3. Academics" },
    { label: "Communication", href: "/admin/announcements", icon: Megaphone, group: "4. Communication" },
    { label: "Setup Wizard", href: "/admin/setup", icon: Settings, group: "5. System" },
    { label: "Settings", href: "/admin/settings", icon: Settings, group: "5. System" },
    { label: "Academic Calendar", href: "/admin/settings/academic-calendar", icon: CalendarCheck, group: "5. System" },
    { label: "Branding", href: "/admin/settings/branding", icon: Settings, group: "5. System" },
  ],
  HEAD_OF_SCHOOL: [
    { label: "Dashboard", href: "/admin/dashboard", icon: LayoutDashboard, group: "1. Admin" },
    { label: "Reception", href: "/admin/reception", icon: Users, group: "1. Admin" },
    {
      label: "Students",
      href: "/admin/students",
      icon: Users,
      group: "1. Admin",
      children: [
        { label: "All Students", href: "/admin/students", icon: Users, isSubmenu: true },
        { label: "Admissions", href: "/admin/students/admissions", icon: GraduationCap, isSubmenu: true },
        { label: "Transfers", href: "/admin/students/transfers", icon: GraduationCap, isSubmenu: true },
        { label: "Student Settings", href: "/admin/settings/students", icon: Settings, isSubmenu: true },
      ],
    },
    { label: "Parents", href: "/admin/parents", icon: Users, group: "1. Admin" },
    { label: "Teachers", href: "/admin/teachers", icon: GraduationCap, group: "1. Admin" },
    { label: "Driver & Transport", href: "/admin/transport", icon: Building2, group: "1. Admin" },
    { label: "Finance", href: "/admin/finance", icon: CreditCard, group: "2. Finance" },
    { label: "Fee Group & Structure", href: "/admin/fees", icon: CreditCard, group: "2. Finance" },
    { label: "Bills", href: "/admin/invoices", icon: Receipt, group: "2. Finance" },
    { label: "Payments", href: "/admin/payments", icon: CreditCard, group: "2. Finance" },
    { label: "Academics", href: "/admin/academics", icon: BookOpen, group: "3. Academics" },
    { label: "Classes & Arms", href: "/admin/classes", icon: Building2, group: "3. Academics" },
    { label: "Subjects", href: "/admin/subjects", icon: BookOpen, group: "3. Academics" },
    { label: "Attendance", href: "/admin/attendance", icon: CalendarCheck, group: "3. Academics" },
    { label: "Results", href: "/admin/results", icon: FileBarChart, group: "3. Academics" },
    { label: "LMS", href: "/admin/lms", icon: BookOpen, group: "3. Academics" },
    { label: "Communication", href: "/admin/announcements", icon: Megaphone, group: "4. Communication" },
    { label: "Setup Wizard", href: "/admin/setup", icon: Settings, group: "5. System" },
    { label: "Settings", href: "/admin/settings", icon: Settings, group: "5. System" },
    { label: "Academic Calendar", href: "/admin/settings/academic-calendar", icon: CalendarCheck, group: "5. System" },
    { label: "Branding", href: "/admin/settings/branding", icon: Settings, group: "5. System" },
  ],
  PRINCIPAL: [
    { label: "Dashboard", href: "/admin/dashboard", icon: LayoutDashboard },
    { label: "Academic Calendar", href: "/admin/settings/academic-calendar", icon: CalendarCheck },
  ],
  ACCOUNTANT: [
    { label: "Dashboard", href: "/accountant/dashboard", icon: LayoutDashboard },
    { label: "Fee Setup", href: "/accountant/fee-setup", icon: CreditCard },
    { label: "Bills", href: "/accountant/invoices", icon: Receipt },
    { label: "Payments", href: "/accountant/payments", icon: CreditCard },
    { label: "Receipts", href: "/accountant/receipts", icon: Receipt },
    { label: "Debtors", href: "/accountant/debtors", icon: FileBarChart },
    { label: "Discounts", href: "/accountant/discounts", icon: CreditCard },
    { label: "Finance Reports", href: "/accountant/finance-reports", icon: FileBarChart },
  ],
  TEACHER: [
    { label: "Dashboard", href: "/teacher/dashboard", icon: LayoutDashboard },
    { label: "My Profile", href: "/teacher/profile", icon: Users },
    { label: "My Classes", href: "/teacher/my-classes", icon: Building2 },
    { label: "My Subjects", href: "/teacher/my-subjects", icon: BookOpen },
    { label: "Attendance", href: "/teacher/attendance", icon: CalendarCheck },
    { label: "Score Entry", href: "/teacher/score-entry", icon: FileBarChart },
    { label: "Assignments", href: "/teacher/assignments", icon: BookOpen },
    { label: "Lesson Notes", href: "/teacher/lesson-notes", icon: BookOpen },
    { label: "Timetable", href: "/teacher/timetable", icon: CalendarCheck },
    { label: "Student Reports", href: "/teacher/student-reports", icon: FileBarChart },
    { label: "LMS", href: "/teacher/lms", icon: BookOpen },
    { label: "Announcements", href: "/teacher/announcements", icon: Megaphone },
  ],
  PARENT: [
    { label: "Dashboard", href: "/parent/dashboard", icon: LayoutDashboard },
    { label: "Profile", href: "/parent/profile", icon: Users },
    { label: "My Children", href: "/parent/children", icon: Users },
    { label: "Fees & Bills", href: "/parent/fees", icon: CreditCard },
    { label: "Payments", href: "/parent/payments", icon: CreditCard },
    { label: "Attendance", href: "/parent/attendance", icon: CalendarCheck },
    { label: "Results", href: "/parent/results", icon: FileBarChart },
    { label: "Report Cards", href: "/parent/report-cards", icon: FileBarChart },
    { label: "School Calendar", href: "/parent/school-calendar", icon: CalendarCheck },
    { label: "Messages", href: "/parent/messages", icon: Megaphone },
    { label: "Complaints", href: "/parent/complaints", icon: MessageSquareWarning },
    { label: "Announcements", href: "/parent/announcements", icon: Megaphone },
    { label: "LMS", href: "/parent/lms", icon: BookOpen },
  ],
  STUDENT: [
    { label: "Dashboard", href: "/student/dashboard", icon: LayoutDashboard },
    { label: "My Profile", href: "/student/profile", icon: Users },
    { label: "Subjects", href: "/student/subjects", icon: BookOpen },
    { label: "Timetable", href: "/student/timetable", icon: CalendarCheck },
    { label: "Assignments", href: "/student/assignments", icon: BookOpen },
    { label: "Attendance", href: "/student/attendance", icon: CalendarCheck },
    { label: "LMS", href: "/student/lms", icon: BookOpen },
    { label: "Results", href: "/student/results", icon: FileBarChart },
    { label: "Report Card", href: "/student/report-card", icon: FileBarChart },
    { label: "Announcements", href: "/student/announcements", icon: Megaphone },
  ],
  REGISTRAR: [
    { label: "Dashboard", href: "/registrar/dashboard", icon: LayoutDashboard },
    { label: "Applications", href: "/registrar/applications", icon: Users },
    { label: "Admissions", href: "/registrar/admissions", icon: Users },
    { label: "Student Records", href: "/registrar/student-records", icon: Users },
    { label: "Class Placement", href: "/registrar/class-placement", icon: Building2 },
    { label: "Parent Records", href: "/registrar/parent-records", icon: Users },
    { label: "Documents", href: "/registrar/documents", icon: FileBarChart },
    { label: "ID Cards", href: "/registrar/id-cards", icon: FileBarChart },
  ],
};
