import type { LucideIcon } from "lucide-react";
import {
  BookOpen,
  Building2,
  CalendarCheck,
  CalendarDays,
  ClipboardList,
  CreditCard,
  Database,
  DollarSign,
  FileBarChart,
  FileCode,
  FileText,
  GraduationCap,
  HelpCircle,
  LayoutDashboard,
  Mail,
  Map,
  Megaphone,
  MessageSquareWarning,
  Palette,
  PhoneCall,
  Receipt,
  School,
  Settings,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  TrendingDown,
  TrendingUp,
  UserCog,
  Users,
  Wallet,
} from "lucide-react";

export type NavItem = {
  label: string;
  href: string;
  icon: LucideIcon;
  group?: string;
  children?: NavItem[];
  isSubmenu?: boolean;
};

export const navByRole: Record<string, NavItem[]> = {
  SUPER_ADMIN: [
    { label: "Dashboard", href: "/admin/dashboard", icon: LayoutDashboard, group: "1. Admin" },
    {
      label: "Reception",
      href: "/admin/reception",
      icon: Users,
      group: "1. Admin",
      children: [
        { label: "Reception Dashboard", href: "/admin/reception/dashboard", icon: LayoutDashboard, isSubmenu: true },
        { label: "Enquiries", href: "/admin/reception/enquiry", icon: HelpCircle, isSubmenu: true },
        { label: "Visitors", href: "/admin/reception", icon: Users, isSubmenu: true },
        { label: "Call Log", href: "/admin/reception/call-log", icon: PhoneCall, isSubmenu: true },
        { label: "Complaints", href: "/admin/reception/complaint", icon: MessageSquareWarning, isSubmenu: true },
        { label: "Correspondence", href: "/admin/reception/correspondence", icon: Mail, isSubmenu: true },
        { label: "Gate Pass", href: "/admin/reception/gate-pass", icon: FileText, isSubmenu: true },
        { label: "Queries", href: "/admin/reception/query", icon: HelpCircle, isSubmenu: true },
      ],
    },
    {
      label: "Students",
      href: "/admin/students",
      icon: GraduationCap,
      group: "1. Admin",
      children: [
        { label: "All Students", href: "/admin/students", icon: Users, isSubmenu: true },
        { label: "Admissions", href: "/admin/students/admissions", icon: GraduationCap, isSubmenu: true },
        { label: "Transfers", href: "/admin/students/transfers", icon: GraduationCap, isSubmenu: true },
        { label: "Student Settings", href: "/admin/settings/students", icon: Settings, isSubmenu: true },
      ],
    },
    { label: "Parents", href: "/admin/parents", icon: Users, group: "1. Admin" },
    { label: "Teachers", href: "/admin/teachers", icon: GraduationCap, group: "1. Admin" },
    { label: "Driver & Transport", href: "/admin/transport", icon: Building2, group: "1. Admin" },
    {
      label: "Finance",
      href: "/admin/finance",
      icon: DollarSign,
      group: "2. Finance",
      children: [
        { label: "Finance Overview", href: "/admin/finance", icon: DollarSign, isSubmenu: true },
        { label: "Fee Group & Structure", href: "/admin/fees", icon: CreditCard, isSubmenu: true },
        { label: "Bills", href: "/admin/invoices", icon: Receipt, isSubmenu: true },
        { label: "Payments", href: "/admin/payments", icon: CreditCard, isSubmenu: true },
        { label: "Income", href: "/admin/income", icon: TrendingUp, isSubmenu: true },
        { label: "Expenses", href: "/admin/expenses", icon: TrendingDown, isSubmenu: true },
        { label: "Debtors", href: "/admin/debtors", icon: FileBarChart, isSubmenu: true },
        { label: "Ledger", href: "/admin/ledger", icon: FileBarChart, isSubmenu: true },
        { label: "Revenue", href: "/admin/revenue", icon: TrendingUp, isSubmenu: true },
      ],
    },
    {
      label: "Academics",
      href: "/admin/academics",
      icon: BookOpen,
      group: "3. Academics",
      children: [
        { label: "Academic Overview", href: "/admin/academics", icon: BookOpen, isSubmenu: true },
        { label: "Classes & Arms", href: "/admin/classes", icon: Building2, isSubmenu: true },
        { label: "Class Mapping", href: "/admin/classes/mapping", icon: Map, isSubmenu: true },
        { label: "Subjects", href: "/admin/subjects", icon: BookOpen, isSubmenu: true },
        { label: "Assessments", href: "/admin/assessments", icon: ClipboardList, isSubmenu: true },
        { label: "Attendance", href: "/admin/attendance", icon: CalendarCheck, isSubmenu: true },
        { label: "Results", href: "/admin/results", icon: FileBarChart, isSubmenu: true },
        { label: "LMS", href: "/admin/lms", icon: BookOpen, isSubmenu: true },
      ],
    },
    {
      label: "Communication",
      href: "/admin/announcements",
      icon: Megaphone,
      group: "4. Communication",
      children: [
        { label: "Announcements", href: "/admin/announcements", icon: Megaphone, isSubmenu: true },
        { label: "Messages", href: "/admin/messages", icon: Mail, isSubmenu: true },
        { label: "Complaints", href: "/admin/reception/complaint", icon: MessageSquareWarning, isSubmenu: true },
      ],
    },
    {
      label: "System",
      href: "/admin/settings",
      icon: Settings,
      group: "5. System",
      children: [
        { label: "Setup Wizard", href: "/admin/setup", icon: Settings, isSubmenu: true },
        { label: "General Settings", href: "/admin/settings", icon: Settings, isSubmenu: true },
        { label: "School Profile", href: "/admin/settings/school", icon: School, isSubmenu: true },
        { label: "Configuration Engine", href: "/admin/settings/config-engine", icon: SlidersHorizontal, isSubmenu: true },
        { label: "Users", href: "/admin/settings/users", icon: UserCog, isSubmenu: true },
        { label: "Roles", href: "/admin/roles", icon: Shield, isSubmenu: true },
        { label: "Privileges", href: "/admin/privileges", icon: ShieldCheck, isSubmenu: true },
        { label: "Academic Calendar", href: "/admin/settings/academic-calendar", icon: CalendarDays, isSubmenu: true },
        { label: "Grading Setup", href: "/admin/settings/grading", icon: GraduationCap, isSubmenu: true },
        { label: "Master Data", href: "/admin/settings/master-data", icon: Database, isSubmenu: true },
        { label: "Payment Methods", href: "/admin/settings/payment-methods", icon: Wallet, isSubmenu: true },
        { label: "Reception Settings", href: "/admin/settings/reception", icon: PhoneCall, isSubmenu: true },
        { label: "Report Templates", href: "/admin/settings/templates", icon: FileCode, isSubmenu: true },
        { label: "Branding", href: "/admin/settings/branding", icon: Palette, isSubmenu: true },
        { label: "My Profile", href: "/admin/profile", icon: UserCog, isSubmenu: true },
      ],
    },
  ],
  SCHOOL_ADMIN: [
    { label: "Dashboard", href: "/admin/dashboard", icon: LayoutDashboard, group: "1. Admin" },
    {
      label: "Reception",
      href: "/admin/reception",
      icon: Users,
      group: "1. Admin",
      children: [
        { label: "Reception Dashboard", href: "/admin/reception/dashboard", icon: LayoutDashboard, isSubmenu: true },
        { label: "Enquiries", href: "/admin/reception/enquiry", icon: HelpCircle, isSubmenu: true },
        { label: "Visitors", href: "/admin/reception", icon: Users, isSubmenu: true },
        { label: "Call Log", href: "/admin/reception/call-log", icon: PhoneCall, isSubmenu: true },
        { label: "Complaints", href: "/admin/reception/complaint", icon: MessageSquareWarning, isSubmenu: true },
        { label: "Correspondence", href: "/admin/reception/correspondence", icon: Mail, isSubmenu: true },
        { label: "Gate Pass", href: "/admin/reception/gate-pass", icon: FileText, isSubmenu: true },
        { label: "Queries", href: "/admin/reception/query", icon: HelpCircle, isSubmenu: true },
      ],
    },
    {
      label: "Students",
      href: "/admin/students",
      icon: GraduationCap,
      group: "1. Admin",
      children: [
        { label: "All Students", href: "/admin/students", icon: Users, isSubmenu: true },
        { label: "Admissions", href: "/admin/students/admissions", icon: GraduationCap, isSubmenu: true },
        { label: "Transfers", href: "/admin/students/transfers", icon: GraduationCap, isSubmenu: true },
        { label: "Student Settings", href: "/admin/settings/students", icon: Settings, isSubmenu: true },
      ],
    },
    { label: "Parents", href: "/admin/parents", icon: Users, group: "1. Admin" },
    { label: "Teachers", href: "/admin/teachers", icon: GraduationCap, group: "1. Admin" },
    { label: "Driver & Transport", href: "/admin/transport", icon: Building2, group: "1. Admin" },
    {
      label: "Finance",
      href: "/admin/finance",
      icon: DollarSign,
      group: "2. Finance",
      children: [
        { label: "Finance Overview", href: "/admin/finance", icon: DollarSign, isSubmenu: true },
        { label: "Fee Group & Structure", href: "/admin/fees", icon: CreditCard, isSubmenu: true },
        { label: "Bills", href: "/admin/invoices", icon: Receipt, isSubmenu: true },
        { label: "Payments", href: "/admin/payments", icon: CreditCard, isSubmenu: true },
        { label: "Income", href: "/admin/income", icon: TrendingUp, isSubmenu: true },
        { label: "Expenses", href: "/admin/expenses", icon: TrendingDown, isSubmenu: true },
        { label: "Debtors", href: "/admin/debtors", icon: FileBarChart, isSubmenu: true },
        { label: "Ledger", href: "/admin/ledger", icon: FileBarChart, isSubmenu: true },
        { label: "Revenue", href: "/admin/revenue", icon: TrendingUp, isSubmenu: true },
      ],
    },
    {
      label: "Academics",
      href: "/admin/academics",
      icon: BookOpen,
      group: "3. Academics",
      children: [
        { label: "Academic Overview", href: "/admin/academics", icon: BookOpen, isSubmenu: true },
        { label: "Classes & Arms", href: "/admin/classes", icon: Building2, isSubmenu: true },
        { label: "Class Mapping", href: "/admin/classes/mapping", icon: Map, isSubmenu: true },
        { label: "Subjects", href: "/admin/subjects", icon: BookOpen, isSubmenu: true },
        { label: "Assessments", href: "/admin/assessments", icon: ClipboardList, isSubmenu: true },
        { label: "Attendance", href: "/admin/attendance", icon: CalendarCheck, isSubmenu: true },
        { label: "Results", href: "/admin/results", icon: FileBarChart, isSubmenu: true },
        { label: "LMS", href: "/admin/lms", icon: BookOpen, isSubmenu: true },
      ],
    },
    {
      label: "Communication",
      href: "/admin/announcements",
      icon: Megaphone,
      group: "4. Communication",
      children: [
        { label: "Announcements", href: "/admin/announcements", icon: Megaphone, isSubmenu: true },
        { label: "Messages", href: "/admin/messages", icon: Mail, isSubmenu: true },
        { label: "Complaints", href: "/admin/reception/complaint", icon: MessageSquareWarning, isSubmenu: true },
      ],
    },
    {
      label: "System",
      href: "/admin/settings",
      icon: Settings,
      group: "5. System",
      children: [
        { label: "Setup Wizard", href: "/admin/setup", icon: Settings, isSubmenu: true },
        { label: "General Settings", href: "/admin/settings", icon: Settings, isSubmenu: true },
        { label: "School Profile", href: "/admin/settings/school", icon: School, isSubmenu: true },
        { label: "Configuration Engine", href: "/admin/settings/config-engine", icon: SlidersHorizontal, isSubmenu: true },
        { label: "Users", href: "/admin/settings/users", icon: UserCog, isSubmenu: true },
        { label: "Roles", href: "/admin/roles", icon: Shield, isSubmenu: true },
        { label: "Privileges", href: "/admin/privileges", icon: ShieldCheck, isSubmenu: true },
        { label: "Academic Calendar", href: "/admin/settings/academic-calendar", icon: CalendarDays, isSubmenu: true },
        { label: "Grading Setup", href: "/admin/settings/grading", icon: GraduationCap, isSubmenu: true },
        { label: "Master Data", href: "/admin/settings/master-data", icon: Database, isSubmenu: true },
        { label: "Payment Methods", href: "/admin/settings/payment-methods", icon: Wallet, isSubmenu: true },
        { label: "Reception Settings", href: "/admin/settings/reception", icon: PhoneCall, isSubmenu: true },
        { label: "Report Templates", href: "/admin/settings/templates", icon: FileCode, isSubmenu: true },
        { label: "Branding", href: "/admin/settings/branding", icon: Palette, isSubmenu: true },
        { label: "My Profile", href: "/admin/profile", icon: UserCog, isSubmenu: true },
      ],
    },
  ],
  HEAD_OF_SCHOOL: [
    { label: "Dashboard", href: "/admin/dashboard", icon: LayoutDashboard, group: "1. Admin" },
    {
      label: "Reception",
      href: "/admin/reception",
      icon: Users,
      group: "1. Admin",
      children: [
        { label: "Reception Dashboard", href: "/admin/reception/dashboard", icon: LayoutDashboard, isSubmenu: true },
        { label: "Enquiries", href: "/admin/reception/enquiry", icon: HelpCircle, isSubmenu: true },
        { label: "Visitors", href: "/admin/reception", icon: Users, isSubmenu: true },
        { label: "Call Log", href: "/admin/reception/call-log", icon: PhoneCall, isSubmenu: true },
        { label: "Complaints", href: "/admin/reception/complaint", icon: MessageSquareWarning, isSubmenu: true },
        { label: "Correspondence", href: "/admin/reception/correspondence", icon: Mail, isSubmenu: true },
        { label: "Gate Pass", href: "/admin/reception/gate-pass", icon: FileText, isSubmenu: true },
        { label: "Queries", href: "/admin/reception/query", icon: HelpCircle, isSubmenu: true },
      ],
    },
    {
      label: "Students",
      href: "/admin/students",
      icon: GraduationCap,
      group: "1. Admin",
      children: [
        { label: "All Students", href: "/admin/students", icon: Users, isSubmenu: true },
        { label: "Admissions", href: "/admin/students/admissions", icon: GraduationCap, isSubmenu: true },
        { label: "Transfers", href: "/admin/students/transfers", icon: GraduationCap, isSubmenu: true },
        { label: "Student Settings", href: "/admin/settings/students", icon: Settings, isSubmenu: true },
      ],
    },
    { label: "Parents", href: "/admin/parents", icon: Users, group: "1. Admin" },
    { label: "Teachers", href: "/admin/teachers", icon: GraduationCap, group: "1. Admin" },
    { label: "Driver & Transport", href: "/admin/transport", icon: Building2, group: "1. Admin" },
    {
      label: "Finance",
      href: "/admin/finance",
      icon: DollarSign,
      group: "2. Finance",
      children: [
        { label: "Finance Overview", href: "/admin/finance", icon: DollarSign, isSubmenu: true },
        { label: "Fee Group & Structure", href: "/admin/fees", icon: CreditCard, isSubmenu: true },
        { label: "Bills", href: "/admin/invoices", icon: Receipt, isSubmenu: true },
        { label: "Payments", href: "/admin/payments", icon: CreditCard, isSubmenu: true },
        { label: "Income", href: "/admin/income", icon: TrendingUp, isSubmenu: true },
        { label: "Expenses", href: "/admin/expenses", icon: TrendingDown, isSubmenu: true },
        { label: "Debtors", href: "/admin/debtors", icon: FileBarChart, isSubmenu: true },
        { label: "Ledger", href: "/admin/ledger", icon: FileBarChart, isSubmenu: true },
        { label: "Revenue", href: "/admin/revenue", icon: TrendingUp, isSubmenu: true },
      ],
    },
    {
      label: "Academics",
      href: "/admin/academics",
      icon: BookOpen,
      group: "3. Academics",
      children: [
        { label: "Academic Overview", href: "/admin/academics", icon: BookOpen, isSubmenu: true },
        { label: "Classes & Arms", href: "/admin/classes", icon: Building2, isSubmenu: true },
        { label: "Class Mapping", href: "/admin/classes/mapping", icon: Map, isSubmenu: true },
        { label: "Subjects", href: "/admin/subjects", icon: BookOpen, isSubmenu: true },
        { label: "Assessments", href: "/admin/assessments", icon: ClipboardList, isSubmenu: true },
        { label: "Attendance", href: "/admin/attendance", icon: CalendarCheck, isSubmenu: true },
        { label: "Results", href: "/admin/results", icon: FileBarChart, isSubmenu: true },
        { label: "LMS", href: "/admin/lms", icon: BookOpen, isSubmenu: true },
      ],
    },
    {
      label: "Communication",
      href: "/admin/announcements",
      icon: Megaphone,
      group: "4. Communication",
      children: [
        { label: "Announcements", href: "/admin/announcements", icon: Megaphone, isSubmenu: true },
        { label: "Messages", href: "/admin/messages", icon: Mail, isSubmenu: true },
        { label: "Complaints", href: "/admin/reception/complaint", icon: MessageSquareWarning, isSubmenu: true },
      ],
    },
    {
      label: "System",
      href: "/admin/settings",
      icon: Settings,
      group: "5. System",
      children: [
        { label: "Setup Wizard", href: "/admin/setup", icon: Settings, isSubmenu: true },
        { label: "General Settings", href: "/admin/settings", icon: Settings, isSubmenu: true },
        { label: "School Profile", href: "/admin/settings/school", icon: School, isSubmenu: true },
        { label: "Configuration Engine", href: "/admin/settings/config-engine", icon: SlidersHorizontal, isSubmenu: true },
        { label: "Users", href: "/admin/settings/users", icon: UserCog, isSubmenu: true },
        { label: "Roles", href: "/admin/roles", icon: Shield, isSubmenu: true },
        { label: "Privileges", href: "/admin/privileges", icon: ShieldCheck, isSubmenu: true },
        { label: "Academic Calendar", href: "/admin/settings/academic-calendar", icon: CalendarDays, isSubmenu: true },
        { label: "Grading Setup", href: "/admin/settings/grading", icon: GraduationCap, isSubmenu: true },
        { label: "Master Data", href: "/admin/settings/master-data", icon: Database, isSubmenu: true },
        { label: "Payment Methods", href: "/admin/settings/payment-methods", icon: Wallet, isSubmenu: true },
        { label: "Reception Settings", href: "/admin/settings/reception", icon: PhoneCall, isSubmenu: true },
        { label: "Report Templates", href: "/admin/settings/templates", icon: FileCode, isSubmenu: true },
        { label: "Branding", href: "/admin/settings/branding", icon: Palette, isSubmenu: true },
        { label: "My Profile", href: "/admin/profile", icon: UserCog, isSubmenu: true },
      ],
    },
  ],
  PRINCIPAL: [
    { label: "Dashboard", href: "/admin/dashboard", icon: LayoutDashboard, group: "1. Admin" },
    {
      label: "Reception",
      href: "/admin/reception",
      icon: Users,
      group: "1. Admin",
      children: [
        { label: "Reception Dashboard", href: "/admin/reception/dashboard", icon: LayoutDashboard, isSubmenu: true },
        { label: "Enquiries", href: "/admin/reception/enquiry", icon: HelpCircle, isSubmenu: true },
        { label: "Visitors", href: "/admin/reception", icon: Users, isSubmenu: true },
        { label: "Call Log", href: "/admin/reception/call-log", icon: PhoneCall, isSubmenu: true },
        { label: "Complaints", href: "/admin/reception/complaint", icon: MessageSquareWarning, isSubmenu: true },
        { label: "Correspondence", href: "/admin/reception/correspondence", icon: Mail, isSubmenu: true },
        { label: "Gate Pass", href: "/admin/reception/gate-pass", icon: FileText, isSubmenu: true },
        { label: "Queries", href: "/admin/reception/query", icon: HelpCircle, isSubmenu: true },
      ],
    },
    {
      label: "Students",
      href: "/admin/students",
      icon: GraduationCap,
      group: "1. Admin",
      children: [
        { label: "All Students", href: "/admin/students", icon: Users, isSubmenu: true },
        { label: "Admissions", href: "/admin/students/admissions", icon: GraduationCap, isSubmenu: true },
        { label: "Transfers", href: "/admin/students/transfers", icon: GraduationCap, isSubmenu: true },
        { label: "Student Settings", href: "/admin/settings/students", icon: Settings, isSubmenu: true },
      ],
    },
    { label: "Parents", href: "/admin/parents", icon: Users, group: "1. Admin" },
    { label: "Teachers", href: "/admin/teachers", icon: GraduationCap, group: "1. Admin" },
    { label: "Driver & Transport", href: "/admin/transport", icon: Building2, group: "1. Admin" },
    {
      label: "Finance",
      href: "/admin/finance",
      icon: DollarSign,
      group: "2. Finance",
      children: [
        { label: "Finance Overview", href: "/admin/finance", icon: DollarSign, isSubmenu: true },
        { label: "Fee Group & Structure", href: "/admin/fees", icon: CreditCard, isSubmenu: true },
        { label: "Bills", href: "/admin/invoices", icon: Receipt, isSubmenu: true },
        { label: "Payments", href: "/admin/payments", icon: CreditCard, isSubmenu: true },
        { label: "Income", href: "/admin/income", icon: TrendingUp, isSubmenu: true },
        { label: "Expenses", href: "/admin/expenses", icon: TrendingDown, isSubmenu: true },
        { label: "Debtors", href: "/admin/debtors", icon: FileBarChart, isSubmenu: true },
        { label: "Ledger", href: "/admin/ledger", icon: FileBarChart, isSubmenu: true },
        { label: "Revenue", href: "/admin/revenue", icon: TrendingUp, isSubmenu: true },
      ],
    },
    {
      label: "Academics",
      href: "/admin/academics",
      icon: BookOpen,
      group: "3. Academics",
      children: [
        { label: "Academic Overview", href: "/admin/academics", icon: BookOpen, isSubmenu: true },
        { label: "Classes & Arms", href: "/admin/classes", icon: Building2, isSubmenu: true },
        { label: "Class Mapping", href: "/admin/classes/mapping", icon: Map, isSubmenu: true },
        { label: "Subjects", href: "/admin/subjects", icon: BookOpen, isSubmenu: true },
        { label: "Assessments", href: "/admin/assessments", icon: ClipboardList, isSubmenu: true },
        { label: "Attendance", href: "/admin/attendance", icon: CalendarCheck, isSubmenu: true },
        { label: "Results", href: "/admin/results", icon: FileBarChart, isSubmenu: true },
        { label: "LMS", href: "/admin/lms", icon: BookOpen, isSubmenu: true },
      ],
    },
    {
      label: "Communication",
      href: "/admin/announcements",
      icon: Megaphone,
      group: "4. Communication",
      children: [
        { label: "Announcements", href: "/admin/announcements", icon: Megaphone, isSubmenu: true },
        { label: "Messages", href: "/admin/messages", icon: Mail, isSubmenu: true },
        { label: "Complaints", href: "/admin/reception/complaint", icon: MessageSquareWarning, isSubmenu: true },
      ],
    },
    {
      label: "System",
      href: "/admin/settings",
      icon: Settings,
      group: "5. System",
      children: [
        { label: "General Settings", href: "/admin/settings", icon: Settings, isSubmenu: true },
        { label: "School Profile", href: "/admin/settings/school", icon: School, isSubmenu: true },
        { label: "Configuration Engine", href: "/admin/settings/config-engine", icon: SlidersHorizontal, isSubmenu: true },
        { label: "Users", href: "/admin/settings/users", icon: UserCog, isSubmenu: true },
        { label: "Roles", href: "/admin/roles", icon: Shield, isSubmenu: true },
        { label: "Privileges", href: "/admin/privileges", icon: ShieldCheck, isSubmenu: true },
        { label: "Academic Calendar", href: "/admin/settings/academic-calendar", icon: CalendarDays, isSubmenu: true },
        { label: "Grading Setup", href: "/admin/settings/grading", icon: GraduationCap, isSubmenu: true },
        { label: "Master Data", href: "/admin/settings/master-data", icon: Database, isSubmenu: true },
        { label: "Payment Methods", href: "/admin/settings/payment-methods", icon: Wallet, isSubmenu: true },
        { label: "Reception Settings", href: "/admin/settings/reception", icon: PhoneCall, isSubmenu: true },
        { label: "Report Templates", href: "/admin/settings/templates", icon: FileCode, isSubmenu: true },
        { label: "Branding", href: "/admin/settings/branding", icon: Palette, isSubmenu: true },
        { label: "My Profile", href: "/admin/profile", icon: UserCog, isSubmenu: true },
      ],
    },
  ],
  ACCOUNTANT: [
    { label: "Dashboard", href: "/accountant/dashboard", icon: LayoutDashboard, group: "1. Overview" },
    { label: "Fee Setup", href: "/accountant/fee-setup", icon: CreditCard, group: "2. Billing" },
    { label: "Bills", href: "/accountant/invoices", icon: Receipt, group: "2. Billing" },
    { label: "Payments", href: "/accountant/payments", icon: CreditCard, group: "2. Billing" },
    { label: "Receipts", href: "/accountant/receipts", icon: Receipt, group: "2. Billing" },
    { label: "Debtors", href: "/accountant/debtors", icon: FileBarChart, group: "3. Financials" },
    { label: "Discounts", href: "/accountant/discounts", icon: CreditCard, group: "3. Financials" },
    { label: "Finance Reports", href: "/accountant/finance-reports", icon: FileBarChart, group: "3. Financials" },
  ],
  TEACHER: [
    { label: "Dashboard", href: "/teacher/dashboard", icon: LayoutDashboard, group: "1. Overview" },
    { label: "My Profile", href: "/teacher/profile", icon: Users, group: "1. Overview" },
    { label: "My Classes", href: "/teacher/my-classes", icon: Building2, group: "2. Academics" },
    { label: "My Subjects", href: "/teacher/my-subjects", icon: BookOpen, group: "2. Academics" },
    { label: "Attendance", href: "/teacher/attendance", icon: CalendarCheck, group: "2. Academics" },
    { label: "Score Entry", href: "/teacher/score-entry", icon: FileBarChart, group: "2. Academics" },
    { label: "Assignments", href: "/teacher/assignments", icon: BookOpen, group: "3. Teaching" },
    { label: "Lesson Notes", href: "/teacher/lesson-notes", icon: BookOpen, group: "3. Teaching" },
    { label: "Timetable", href: "/teacher/timetable", icon: CalendarCheck, group: "3. Teaching" },
    { label: "Student Reports", href: "/teacher/student-reports", icon: FileBarChart, group: "3. Teaching" },
    { label: "LMS", href: "/teacher/lms", icon: BookOpen, group: "3. Teaching" },
    { label: "Announcements", href: "/teacher/announcements", icon: Megaphone, group: "4. Communication" },
  ],
  PARENT: [
    { label: "Dashboard", href: "/parent/dashboard", icon: LayoutDashboard, group: "1. Overview" },
    { label: "My Children", href: "/parent/children", icon: Users, group: "1. Overview" },
    { label: "Fees & Bills", href: "/parent/fees", icon: CreditCard, group: "2. Finance" },
    { label: "Payments", href: "/parent/payments", icon: CreditCard, group: "2. Finance" },
    { label: "Attendance", href: "/parent/attendance", icon: CalendarCheck, group: "3. Academics" },
    { label: "Results", href: "/parent/results", icon: FileBarChart, group: "3. Academics" },
    { label: "Report Cards", href: "/parent/report-cards", icon: FileBarChart, group: "3. Academics" },
    { label: "School Calendar", href: "/parent/school-calendar", icon: CalendarCheck, group: "3. Academics" },
    { label: "Messages", href: "/parent/messages", icon: Megaphone, group: "4. Communication" },
    { label: "Complaints", href: "/parent/complaints", icon: MessageSquareWarning, group: "4. Communication" },
    { label: "Announcements", href: "/parent/announcements", icon: Megaphone, group: "4. Communication" },
    { label: "LMS", href: "/parent/lms", icon: BookOpen, group: "5. Learning" },
    { label: "My Profile", href: "/parent/profile", icon: Users, group: "6. Settings" },
  ],
  STUDENT: [
    { label: "Dashboard", href: "/student/dashboard", icon: LayoutDashboard, group: "1. Overview" },
    { label: "My Profile", href: "/student/profile", icon: Users, group: "1. Overview" },
    { label: "Subjects", href: "/student/subjects", icon: BookOpen, group: "2. Academics" },
    { label: "Timetable", href: "/student/timetable", icon: CalendarCheck, group: "2. Academics" },
    { label: "Assignments", href: "/student/assignments", icon: BookOpen, group: "2. Academics" },
    { label: "Attendance", href: "/student/attendance", icon: CalendarCheck, group: "2. Academics" },
    { label: "LMS", href: "/student/lms", icon: BookOpen, group: "3. Learning" },
    { label: "Results", href: "/student/results", icon: FileBarChart, group: "4. Performance" },
    { label: "Report Card", href: "/student/report-card", icon: FileBarChart, group: "4. Performance" },
    { label: "Announcements", href: "/student/announcements", icon: Megaphone, group: "5. Communication" },
  ],
  REGISTRAR: [
    { label: "Dashboard", href: "/registrar/dashboard", icon: LayoutDashboard, group: "1. Overview" },
    { label: "Applications", href: "/registrar/applications", icon: Users, group: "2. Admissions" },
    { label: "Admissions", href: "/registrar/admissions", icon: Users, group: "2. Admissions" },
    { label: "Student Records", href: "/registrar/student-records", icon: Users, group: "3. Records" },
    { label: "Class Placement", href: "/registrar/class-placement", icon: Building2, group: "3. Records" },
    { label: "Parent Records", href: "/registrar/parent-records", icon: Users, group: "3. Records" },
    { label: "Documents", href: "/registrar/documents", icon: FileBarChart, group: "4. Documents" },
    { label: "ID Cards", href: "/registrar/id-cards", icon: FileBarChart, group: "4. Documents" },
  ],
};
